services:

  backend:
    ports:
      - "8000:8000"
    environment:
      SHARED_KEY: ${SHARED_KEY}
    build: .
    volumes:
      - persistence:/var/lib/backend/persistence
volumes:
  persistence:

